### ISSUE TITLE
Unlocking keyboard doesn't work in scanning mode

### ISSUE THREAD

**Issue by qsus** [AubsUK/uv-k5-firmware-custom#17]
Holding F# button to lock and unlock keys does not work in scanning mode. This can brick the radio when auto-locking is enabled, scanning on boot is enabled and lock/unlock is not assigned to any of the side buttons.

**Comment by AubsUK** [comment]
Thanks for the input, I've sorted this out (and also moved the padlock icon over.  If you are able to build it from code yourself it should work straight away.  If you need it in a release, it'll probably be done tomorrow or later in the week after I have a look at the TX option you mentioned in discussion https://github.com/AubsUK/uv-k5-firmware-custom/discussions/16.

**Comment by AubsUK** [comment]
Hello @qsus I've fixed this in release [v00.06](https://github.com/AubsUK/uv-k5-firmware-custom/releases/tag/v00.06).  I'll look into the TX locking separately.
