### ISSUE TITLE
[Feature Request] Channel Browser Lockout

### ISSUE THREAD

**Issue by VA7FGT** [AubsUK/uv-k5-firmware-custom#26]
A menu option to select which lists are viewable from the channel browser may be useful.  

I use my radios for work, so if I can prevent a coworker from accidentally transmitting on a band/power they shouldn't be able to, hitting a repeater, etc before handing off a radio that would be useful. May also be useful for constraining the main menu to frequently used subsets outside of scanning.

No idea if this is workable or not

**Comment by AubsUK** [comment]
I think it would take a lot of precious code for something that would be considered really simple to do.

I also think that someone should be trusted to use devices before they are handed over to them.  As cheap as they are, they aren't toys, and could cause illegal (and harmful / life threatening) interference, especially if transmitting or generating harmonics over emergency services or military frequencies.  If a radio was going to be used in a commercial environment, I would suggest having a purpose-built firmware that does exactly what you want.

**Comment by VA7FGT** [comment]
Not wrong on both counts, I always forget how little space is on these (and we have commercial units I'm transmitting to in their hands anyway). 

Kinda realized it was fluff and closed it, sorry for the trouble
